########################################################################################################################
# Policies shared by all nodes in the fabric. P, PE and RRs
########################################################################################################################
custom_structured_configuration_prefix_lists:
  - name: "DEFAULT_ONLY"
    sequence_numbers:
      - sequence: 10
        action: "permit 0.0.0.0/0"
  - name: "PROVIDER_ROUTES"
    sequence_numbers:
      - sequence: 10
        action: "permit 80.0.0.0/16 le 24"
      - sequence: 20
        action: "permit 81.0.0.0/16 le 24"
      - sequence: 30
        action: "permit 82.0.0.0/16 le 24"

custom_structured_configuration_route_maps:
  - name: "DEFAULT_ONLY"
    sequence_numbers:
      - sequence: 10
        type: "permit"
        match:
          - "ip address prefix-list DEFAULT_ONLY"
      - sequence: 20
        type: "deny"
  - name: "PROVIDER_ROUTES_ONLY"
    sequence_numbers:
      - sequence: 10
        type: "permit"
        match:
          - "ip address prefix-list PROVIDER_ROUTES"
      - sequence: 20
        type: "deny"
