endpoints_pon_shelves:
  - name: "PON_SHELF_BETA"
    adapters:
      - switches: [ "BETA-PE-01", "BETA-PE-02" ]
        switch_ports: [ "Ethernet2", "Ethernet2" ]
        endpoint_ports: [ "CARD A", "CARD B" ]
        sflow: true
        port_channel:
          description: "PON_TRUNK: PON_SHELF_BETA"
          mode: active
          structured_config:
            lacp_id: "3838.a600.0001"
          subinterfaces:
            - number: 1001 # Subinterface ID
              vlan_id: 1001  # services_cgnat SVI 1001
              short_esi: "{{ esi_PON_SHELF_BETA_PUBLIC }}"
              structured_config:
                description: "PON_SERVICE: PON_SHELF_BETA: PUBLIC"
                encapsulation_vlan:
                  client:
                    encapsulation: "dot1q"
                    vlan: 1001
                  network:
            - number: 1002 # Subinteface ID
              vlan_id: 1002 # services_cg_nat SVI 1002
              short_esi: "{{ esi_PON_SHELF_BETA_CGNAT }}"
              structured_config:
                description: "PON_SERVICE: PON_SHELF_BETA: CGNAT"
                encapsulation_vlan:
                  client:
                    encapsulation: "dot1q"
                    vlan: 1002
                  network:
            - number: 1003  # Subinterface ID
              vlan_id: 1003 # services_pon_mgmt SVI 1003
              short_esi: "{{ esi_PON_SHELF_BETA_MGMT }}"
              structured_config:
                description: "PON_SERVICE: PON_SHELF_BETA: Management"
                encapsulation_vlan:
                  client:
                    encapsulation: "dot1q"
                    vlan: 1003
                  network:

  - name: "PON_SHELF_OMNI"
    adapters:
      - switches: [ "DELTA-PE-02", "GAMMA-PE-01" ]
        switch_ports: [ "Ethernet2", "Ethernet2" ]
        endpoint_ports: [ "CARD A", "CARD B" ]
        sflow: true
        port_channel:
          description: "PON_TRUNK: PON_SHELF_OMNI"
          mode: active
          structured_config:
            lacp_id: "3838.a600.0001"
          subinterfaces:
            - number: 1001  # Subinterface ID
              vlan_id: 1001 # services_internet SVI 1004
              short_esi: "{{ esi_PON_SHELF_OMNI_PUBLIC }}"
              structured_config:
                description: "PON_SERVICE: PON_SHELF_OMNI: PUBLIC"
                encapsulation_vlan:
                  client:
                    encapsulation: "dot1q"
                    vlan: 1001
                  network:
            - number: 1004  # Subinterface ID
              vlan_id: 1004 # services_cg_nat SVI 1004
              short_esi: "{{ esi_PON_SHELF_OMNI_CGNAT }}"
              structured_config:
                description: "PON_SERVICE: PON_SHELF_OMNI: CGNAT"
                encapsulation_vlan:
                  client:
                    encapsulation: "dot1q"
                    vlan: 1004
                  network:
            # - number: 1006  # Subinterface ID
            #   vlan_id: 1006 # services_mgmt SVI 1006
            #   short_esi: "{{ esi_PON_SHELF_OMNI_MGMT }}"
            #   structured_config:
            #     description: "PON_SERVICE: PON_SHELF_OMNI: Management"
            #     encapsulation_vlan:
            #       client:
            #         encapsulation: "dot1q"
            #         vlan: 1006
            #       network:
  # USE TRUNK
  # - name: "PON_SHELF_OMNI"
  #   adapters:
  #     - switches: [ "DELTA-PE-02", "GAMMA-PE-01" ]
  #       switch_ports: [ "Ethernet2", "Ethernet2" ]
  #       endpoint_ports: [ "CARD A", "CARD B" ]
  #       ethernet_segment:
  #         short_esi: "9999:0002:0000"
  #       port_channel:
  #         description: "PON_TRUNK: PON_SHELF_OMNI"
  #         mode: active
  #         structured_config:
  #           lacp_id: "3838.a600.0001"
  #       mode: trunk
  #       vlans: "1001, 1002, 1004"
