services_pon_mgmt:
  - name: "PON Management Services"
    mac_vrf_id_base: 10000
    vrfs:
      - name: "PON_MGMT"
        description: "PON MANAGEMENT SERVICES"
        address_families: [ "evpn" ]
        vrf_id: 10000
        vtep_diagnostic:
          loopback: 10
          loopback_description: "PON Management Loopback"
          loopback_ip_range: 172.16.10.0/24
        svis:
          - id: 1003
            name: "PON_SHELF_Y_MGMT"
            ip_address_virtual: "172.31.255.1/24"
          - id: 1006
            name: "PON_SHELF_Z_MGMT"
            ip_address_virtual: "172.31.255.1/24"
