########################################################################################################################
# Policies and profiles shared by all Provider Edge Elements
########################################################################################################################
services_cg_nat:
  - name: "CGNAT_HA_FAILOVER"
    pseudowire_rt_base: 55000
    point_to_point_services:
      - name: "CGNAT_HA_FAILOVER"
        type: "vpws-pseudowire"
        endpoints:
          - id: 1
            nodes: ["ALPHA-PE-01", "ALPHA-PE-02"]
            interfaces: ["Ethernet5", "Ethernet5"]
            port_channel:
              mode: "active"
              short_esi: "{{ esi_CGNAT_HA_PWIRE_A }}"
          - id:  2
            nodes: [ "BETA-PE-01", "BETA-PE-02" ]
            interfaces: [ "Ethernet5", "Ethernet5"]
            port_channel:
              mode: "active"
              short_esi: "{{ esi_CGNAT_HA_PWIRE_Z }}"

  - name: "CG-NAT Customer Data Services"
    mac_vrf_id_base: 50000
    vrfs:
      - name: "CGNAT"
        structured_config:
          vrfs:
            - name: "CGNAT"
              ipv6_routing: true
          # router_general:
          #   control_functions:
          #     code_units:
          #       - name: CGNAT_FILTERS
          #         content: "{{ lookup('file', 'cg_nat_filters.rcf') }}"
        description: "CGNAT"
        address_families: [ "evpn" ]
        vrf_id: 50000
        vtep_diagnostic:
          loopback: 50
          loopback_description: "CG-NAT Loopback"
          loopback_ip_range: 172.16.50.0/24
          loopback_ipv6_range: "2001:db8:8000:50::/64"
        l3_interfaces:
          - nodes: ["ALPHA-EDGE-01"]
            interfaces: ["Ethernet3.20"]
            descriptions: ["CG-NAT-01"]
            ip_addresses: ["198.51.100.15/31"]
          - nodes: ["BETA-EDGE-01"]
            interfaces: ["Ethernet3.20"]
            descriptions: ["CG-NAT-02"]
            ip_addresses: ["198.51.100.17/31"]
        bgp_peer_groups:
          - name: "CGNAT_APPLIANCE_CGNAT_VRF"
            local_as: 64496
            remote_as: 65100
            default_originate:
              enabled: true
              always: true
            route_map_in: "DEFAULT_ONLY"
        bgp_peers:
          - nodes: ["ALPHA-EDGE-01"]
            description: "CG-NAT-01 Port 1"
            peer_group: "CGNAT_APPLIANCE_CGNAT_VRF"
            ip_address: "198.51.100.14"
          - nodes: ["BETA-EDGE-01"]
            description: "CG-NAT-02 Port 1"
            peer_group: "CGNAT_APPLIANCE_CGNAT_VRF"
            ip_address: "198.51.100.16"
        # additional_route_targets:
        #   - type: "import"
        #     address_family: "evpn"
        #     route_target: "65000:30000" # INTERNET VRF
        #   - type: "import"
        #     address_family: "evpn"
        #     route_target: "rcf FILTER_CGNAT_IMPORTS()"
        # PON Virtual Gateways
        svis:
          - id: 1002
            enabled: true
            profile: "CGN DHCP"
            name: "PON_SHELF_BETA_DATA"
            ip_address_virtual: "100.64.0.1/22"
            ipv6_address_virtuals: ["2001:db8:8002:0000::1/64"]
          - id: 1004
            enabled: true
            profile: "CGN DHCP"
            name: "PON_SHELF_OMNI_DATA"
            ip_address_virtual: "100.64.4.1/22"
            ipv6_address_virtuals: ["2001:db8:8002:0001::1/64"]
          # - id: 3999
          #   enabled: true
          #   profile: "CGN DHCP"
          #   name: "PON_SHELF_OMNI_DATA"
          #   ip_address_virtual: "100.64.99.1/22"
          #   ipv6_address_virtuals: ["2001:db8:8002:3999::1/64"]