#######################################################################################
# Voice Services
#######################################################################################
services_voice:
  - name: "PON VOICE SERVICES"
    mac_vrf_id_base: 60000
    vrfs:
      - name: "PON_VOICE"
        description: "PON VOICE SERVICES"
        address_families: [ "evpn" ]
        vrf_id: 60000
        vtep_diagnostic:
          loopback: 60
          loopback_description: "Voice Loopback"
          loopback_ip_range: 172.16.60.0/24
        # svis:
        #   - id: 1002
        #     name: "PON_SHELF_Y_VOICE"
        #     profile: "Voice DHCP"
        #     ip_address_virtual: "172.19.128.1/22"
        #   - id: 1005
        #     name: "PON_SHELF_Z_VOICE"
        #     profile: "Voice DHCP"
        #     ip_address_virtual: "172.19.128.4/22"
