! Command: show running-config
! device: ALPHA-CG-NAT (cEOSLab, EOS-4.36.2F-49009417.eostrunkceos (engineering build))
!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$n5UzLR7bucITZ.fE$BoS3AU71MBIDlSsWb1NpH0P62l9AyanxImmA.9OKesBuClBXXae3oMf0fm1HA.3rxwzvbkbVl.QarZAHgm7V81
username dave.watkins privilege 15 role network-admin secret sha512 $6$n5UzLR7bucITZ.fE$BoS3AU71MBIDlSsWb1NpH0P62l9AyanxImmA.9OKesBuClBXXae3oMf0fm1HA.3rxwzvbkbVl.QarZAHgm7V81
!
management api http-commands
   no shutdown
   !
   vrf OOB
      no shutdown
!
event-monitor
!
no service interface inactive port-id allocation disabled
!
load-interval default 1
!
service routing protocols model multi-agent
!
hostname ALPHA-CG-NAT
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
vrf instance OOB
!
aaa authentication login console local
aaa authorization exec default local
!
interface Ethernet1
   description ALPHA-EDGE-01 Ethernet3 (INTERNET+CGNAT trunk)
   no switchport
!
interface Ethernet1.10
   description INTERNET peering to ALPHA-EDGE-01
   !
   encapsulation vlan
      client dot1q 10
   ip address 198.51.100.6/31
!
interface Ethernet1.20
   description CGNAT peering to ALPHA-EDGE-01
   !
   encapsulation vlan
      client dot1q 20
   ip address 198.51.100.14/31
!
interface Ethernet2
   description ALPHA-PE-01 - reserved, not yet in use
   shutdown
   no switchport
!
interface Ethernet3
   description ALPHA-PE-02 - reserved, not yet in use
   shutdown
   no switchport
!
interface Management0
   description OOB_MANAGEMENT
   vrf OOB
   ip address 192.168.128.210/24
   no lldp transmit
   no lldp receive
!
ip routing
no ip routing vrf OOB
!
ip route 100.64.0.0/16 Null0
ip route vrf OOB 0.0.0.0/0 192.168.128.254
!
router bgp 65100
   router-id 198.51.100.6
   neighbor 198.51.100.7 remote-as 3791
   neighbor 198.51.100.7 description ALPHA-EDGE-01 INTERNET vrf
   neighbor 198.51.100.15 remote-as 64496
   neighbor 198.51.100.15 description ALPHA-EDGE-01 CGNAT vrf
   neighbor 198.51.100.15 default-originate always
   redistribute static
   !
   address-family ipv4
      neighbor 198.51.100.7 activate
      neighbor 198.51.100.15 activate
!
end